import './globals.css';
import Script from 'next/script';

// 단어 데이터 파일들 — public/data/ 에 둠 (현재 디렉터리의 words*.js 파일을 옮김)
const WORD_FILES = [
  '/data/words.js',
  '/data/words-batch1-g1.js',
  '/data/words-batch1-g2.js',
  '/data/words-batch1-g3.js',
  '/data/words-batch1-g4.js',
  '/data/words-batch2-g1.js',
  '/data/words-batch2-g2.js',
  '/data/words-batch2-g3.js',
  '/data/words-batch2-g4.js',
  '/data/words-batch3-g1.js',
  '/data/words-batch3-g2.js',
  '/data/words-batch3-g3.js',
  '/data/words-batch3-g4.js',
  '/data/words-g5.js',
  '/data/words-batch1-g5.js',
  '/data/words-batch2-g5.js',
  '/data/words-batch4-g1.js',
  '/data/words-batch4-g2.js',
  '/data/words-batch4-g3.js',
  '/data/words-batch4-g4.js',
  '/data/words-batch3-g5.js',
  '/data/words-batch5-g1.js',
  '/data/words-batch5-g2.js',
  '/data/words-batch5-g3.js',
  '/data/words-batch5-g4.js',
  '/data/words-batch5-g5.js',
  '/data/words-batch6-g1.js',
  '/data/words-batch6-g2.js',
  '/data/words-batch6-g3.js',
  '/data/words-batch6-g4.js',
  '/data/words-batch6-g5.js',
  '/data/words-batch7-g1.js',
  '/data/words-batch7-g2.js',
  '/data/words-batch7-g3.js',
  '/data/words-batch7-g4.js',
  '/data/words-batch7-g5.js',
  '/data/words-batch8-g1.js',
  '/data/words-batch8-g2.js',
  '/data/words-batch8-g3.js',
  '/data/words-batch8-g4.js',
  '/data/words-batch8-g5.js',
  '/data/words-batch9-g1.js',
  '/data/words-batch9-g2.js',
  '/data/words-batch9-g3.js',
  '/data/words-batch9-g4.js',
  '/data/words-batch9-g5.js',
  '/data/words-batch10-g1.js',
  '/data/words-batch10-g2.js',
  '/data/words-batch10-g3.js',
  '/data/words-batch10-g4.js',
  '/data/words-batch10-g5.js',
  '/data/words-batch11-g1.js',
  '/data/words-batch11-g2.js',
  '/data/words-batch11-g3.js',
  '/data/words-batch11-g4.js',
  '/data/words-batch11-g5.js',
  '/data/words-batch12-g1.js',
  '/data/words-batch12-g2.js',
  '/data/words-batch12-g3.js',
  '/data/words-batch12-g4.js',
  '/data/words-batch12-g5.js',
  '/data/words-batch13-g1.js',
  '/data/words-batch13-g2.js',
  '/data/words-batch13-g4.js',
  '/data/words-batch13-g5.js',
  '/data/words-batch14-g1.js',
  '/data/words-batch14-g2.js',
  '/data/words-batch14-g4.js',
  '/data/words-batch14-g5.js',
  '/data/words-batch15-g1.js',
  '/data/words-batch15-g2.js',
  '/data/words-batch15-g4.js',
  '/data/words-batch15-g5.js',
  '/data/words-batch16-g2.js',
  '/data/words-batch16-g4.js',
  '/data/words-batch16-g5.js',
  '/data/words-batch17-g2.js',
  '/data/words-batch17-g3.js',
  '/data/words-batch17-g4.js',
  '/data/words-batch17-g5.js',
  '/data/words-batch18-g2.js',
  '/data/words-batch18-g3.js',
  '/data/words-batch18-g4.js',
  '/data/words-batch18-g5.js',
  '/data/words-batch19-g2.js',
  '/data/words-batch19-g3.js',
  '/data/words-batch19-g4.js',
  '/data/words-batch19-g5.js',
  '/data/words-batch20-g2.js',
  '/data/words-batch20-g3.js',
  '/data/words-batch20-g4.js',
  '/data/words-batch20-g5.js',
  '/data/words-batch21-g5.js',
  '/data/words-batch22-g5.js',
  '/data/words-batch23-g5.js',
  '/data/words-batch24-g5.js',
  '/data/words-batch25-g5.js',
  '/data/words-batch31-g5.js',
  '/data/words-batch16-g1.js',
  '/data/words-batch21-g2.js',
  '/data/words-batch21-g3.js',
  '/data/words-batch22-g3.js',
  '/data/words-batch23-g3.js',
  '/data/words-batch24-g3.js',
  '/data/words-batch25-g3.js',
  '/data/words-batch26-g3.js',
  '/data/words-batch27-g3.js',
  '/data/words-batch28-g3.js',
  '/data/words-batch29-g3.js',
  '/data/words-batch21-g4.js',
  '/data/words-batch22-g4.js',
  '/data/words-batch23-g4.js',
  '/data/words-batch24-g4.js',
  '/data/words-batch32-g5.js',
  '/data/words-batch33-g5.js',
  '/data/words-batch34-g5.js',
  '/data/words-batch38-g5.js',
  '/data/words-batch39-g5.js',
  '/data/words-batch40-g5.js',
  '/data/words-batch26-g1.js',
  '/data/words-batch27-g1.js',
  '/data/words-batch28-g1.js',
  '/data/words-batch29-g1.js',
  '/data/words-batch22-g2.js',
  '/data/words-batch23-g2.js',
  '/data/words-batch24-g2.js',
  '/data/words-batch30-g3.js',
  '/data/words-batch31-g3.js',
  '/data/words-batch32-g3.js',
  '/data/words-batch33-g3.js',
  '/data/words-batch34-g3.js',
  '/data/words-batch35-g3.js',
  '/data/words-batch36-g3.js',
  '/data/words-batch37-g3.js',
  '/data/words-batch25-g4.js',
  '/data/words-batch26-g4.js',
  '/data/words-batch27-g4.js',
  '/data/words-batch28-g4.js',
  '/data/words-batch35-g5.js',
  '/data/words-batch36-g5.js',
  '/data/words-batch37-g5.js',
  '/data/words-batch41-g5.js',
  '/data/words-batch42-g5.js',
  '/data/words-batch43-g5.js',
  '/data/words-batch44-g5.js',
  '/data/words-batch45-g5.js',
  '/data/words-batch46-g5.js',
  '/data/words-batch47-g5.js',
  '/data/words-batch48-g5.js',
  '/data/words-batch49-g5.js',
  '/data/words-batch25-g2.js',
  '/data/words-batch38-g3.js',
  '/data/words-batch39-g3.js',
  '/data/words-batch29-g4.js',
  '/data/words-batch30-g4.js',
  '/data/words-batch50-g5.js',
  '/data/words-batch51-g5.js',
  '/data/words-batch40-g3.js',
  '/data/words-batch31-g4.js',
  '/data/words-batch52-g5.js',
  '/data/words-batch32-g4.js',
  '/data/words-batch53-g5.js',
  '/data/words-batch54-g5.js',
  '/data/words-batch55-g5.js',
  '/data/words-batch41-g3.js',
  '/data/words-batch33-g4.js',
  '/data/words-batch56-g5.js',
  '/data/words-batch30-g1.js',
  '/data/words-batch26-g2.js',
  '/data/words-batch42-g3.js',
  '/data/words-batch34-g4.js',
  '/data/words-batch57-g5.js',
  '/data/words-batch31-g1.js',
  '/data/words-batch58-g5.js',
  '/data/words-batch59-g5.js',
  '/data/words-batch43-g3.js',
  '/data/words-batch35-g4.js',
  '/data/words-batch60-g5.js',
  '/data/words-final-fill.js',
  '/data/words-final-fill2.js',
  '/data/words-refill-g3.js',
  '/data/words-refill-g4.js',
  '/data/words-refill-g5.js',
  '/data/words-final-fill3.js',
  '/data/words-final-fill4.js',
  '/data/words-final-fill5.js',
  '/data/words-final-fill6.js',
  '/data/words-final-fill7.js',
  '/data/words-final-fill8.js',
  '/data/words-final-fill9.js',
  '/data/words-zipf-refill-g3.js',
  '/data/words-zipf-refill-g4.js',
  '/data/words-zipf-refill-g5.js',
  '/data/words-zipf-big-g3.js',
  '/data/words-zipf-big-g4.js',
  '/data/words-zipf-big-g5.js',
];

export const metadata = {
  title: '우리 가족 영단어',
  description: '영어 단어 학습 앱',
  themeColor: '#ffaec9',
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        {WORD_FILES.map((src) => {
          const basePath = process.env.NEXT_PUBLIC_BASE_PATH || '';
          return <Script key={src} src={`${basePath}${src}`} strategy="beforeInteractive" />;
        })}
        {children}
      </body>
    </html>
  );
}
